Error executing pattern/content-assembler/package.sql: Command failed: lib/pattern/content-assembler/package.sql.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/lib/universal/os-user.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/pattern/typical/typical-cli.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/mod.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/mod.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/domain/domains.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/ddl/table/mod.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/ddl/type.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/ddl/view.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/dialect.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/directive.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/js.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/interpolate.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/sql-notebook.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/polygenix-notebook.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/emit/polygenix.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/polygenix/rust/serde.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/command.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/mod.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/help/mod.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/upgrade/mod.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/action_list.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/boolean.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/child_command.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/command.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/enum.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/file.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/integer.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/number.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/types/string.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/type.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/_errors.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/deprecated.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/lib/universal/record.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/lib/pre-process/psql/mod.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/lib/notebook/chain-of-responsibility.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/_errors.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/flags.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/_utils.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/deps.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/help/_help_generator.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/_utils.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/bash.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/complete.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/fish.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/zsh.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/upgrade/provider/deno_land.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/upgrade/provider/github.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/upgrade/provider/nest_land.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/upgrade/provider.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/upgrade/upgrade_command.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/types/boolean.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/types/integer.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/types/number.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/types/string.ts
[0m[32mDownload[0m https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/lib/universal/graph.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/deprecated.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/_validate_flags.ts
[0m[32mDownload[0m https://deno.land/std@0.170.0/fmt/colors.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/table.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/_utils/distance.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/_bash_completions_generator.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/_fish_completions_generator.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/command/completions/_zsh_completions_generator.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/flags/types.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/border.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/cell.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/layout.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/row.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/utils.ts
[0m[32mDownload[0m https://deno.land/x/cliffy@v0.25.7/table/deps.ts
[0m[1m[31merror[0m: Import 'https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/domain/domains.ts' failed: 429 Too Many Requests
    at [0m[36mhttps://raw.githubusercontent.com/netspective-labs/sql-aide/v0.14.8/render/domain/mod.ts[0m:[0m[33m2[0m:[0m[33m15[0m
