Error executing pattern/compliance-explorer/package.sql: Command failed: lib/pattern/compliance-explorer/package.sql.ts
[0m[32mDownload[0m https://jsr.io/@spry/universal/spawn/shell.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8_meta.json
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/mod.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/basename.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/constants.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/dirname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/extname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/format.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/from_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/is_absolute.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/join.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/normalize.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/parse.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/relative.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/resolve.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/to_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/to_namespaced_path.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/common.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/types.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/glob_to_regexp.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/is_glob.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/join_globs.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/normalize_glob.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_os.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/basename.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/basename.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/dirname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/dirname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/extname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/extname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/format.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/format.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/from_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/from_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/is_absolute.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/is_absolute.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/join.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/join.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/normalize.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/normalize.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/parse.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/parse.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/relative.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/relative.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/resolve.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/resolve.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/to_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/to_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/to_namespaced_path.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/to_namespaced_path.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/common.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/glob_to_regexp.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/glob_to_regexp.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/join_globs.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/join_globs.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/normalize_glob.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/normalize_glob.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/basename.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/strip_trailing_separators.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/_util.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/constants.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/_util.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/dirname.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/assert_path.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/format.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/from_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/normalize.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/normalize_string.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/relative.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/to_file_url.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/_common/glob_to_reg_exp.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/posix/constants.ts
[0m[32mDownload[0m https://jsr.io/@std/path/1.0.8/windows/constants.ts
[0m[1m[31merror[0m: Module not found "https://jsr.io/@spry/universal/spawn/shell.ts".
    at [0m[36mhttps://jsr.io/@spry/universal/1.7.4/doctor.ts[0m:[0m[33m38[0m:[0m[33m36[0m
